policy:
  model_id: /data1/chenweicong/models/Qwen/Qwen2.5-Math-1.5B
  device: cuda:0
  dtype: bfloat16
  attn_implementation: flash_attention_2

vllm:
  model_id: /data1/chenweicong/models/Qwen/Qwen2.5-Math-1.5B
  device: cuda:1
  dtype: bfloat16
  seed: 42

rollout:
  rollout_path: /home/chenweicong/projects/assignment5-alignment/data/hendrycks_math/grpo_rollouts/
  rollout_batch_size: 256
  group_size: 8
  use_std_normalization: true
  advantage_eps: 1e-6
  sampling_temperature: 1.0
  sampling_min_tokens: 4
  sampling_max_tokens: 1024

train:
  run_name: grpo_off_policy_grpo100_b256_ep2
  data_path: /home/chenweicong/projects/assignment5-alignment/data/hendrycks_math/train.jsonl
  train_batch_size: 256
  gradient_accumulation_steps: 128
  n_grpo_steps: 100
  epoch_per_grpo_step: 2
  log_interval: 1
  loss_type: grpo_clip  # options: no_baseline, reinforce_with_baseline, grpo_clip
  grpo_cliprange: 0.2

optimizer:
  lr: 1e-5
  weight_decay: 0.0
  max_grad_norm: 1.0
  betas: [0.9, 0.95]

data:
  prompt_template_path: /home/chenweicong/projects/assignment5-alignment/cs336_alignment/prompts/r1_zero.prompt

eval:
  batch_size: 8
  data_path: /home/chenweicong/projects/assignment5-alignment/data/hendrycks_math/validation.jsonl
  max_eval_samples: 1280
  eval_interval_steps: 10

checkpoint:
  save_dir: ./checkpoints/grpo_qwen2.5_math/grpo_math_off_policy_grpo100_b256_ep2
  save_grpo_interval: 20